version: '3'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./docker/db/data:/var/lib/mysql:rw
    ports:
      - "3307:3306"
